# Generated by Django 5.0.2 on 2024-04-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, unique=True, verbose_name='Add new Department')),
                ('description', models.TextField(default=None, verbose_name='Description here')),
            ],
        ),
    ]
