# Generated by Django 5.0.2 on 2024-03-27 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Comps.complaint'),
        ),
    ]
