# Generated by Django 5.0.2 on 2024-03-07 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Comps.complainttype'),
        ),
    ]
