# Generated by Django 5.0.2 on 2024-03-27 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comps', '0002_alter_comment_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_id',
        ),
    ]
