# Generated by Django 5.0.2 on 2024-03-27 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comps', '0003_rename_user_comment_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
    ]
