# Generated by Django 5.0.2 on 2024-03-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comps', '0003_remove_complaint_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='user_id',
            new_name='user',
        ),
    ]
