# Generated by Django 5.0.2 on 2024-03-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comps', '0004_rename_user_id_complaint_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.IntegerField(choices=[(1, 'InProgress'), (2, 'Solved'), (3, 'Pending')], default=3),
        ),
    ]
