# Generated by Django 5.0.2 on 2024-03-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comps', '0004_rename_user_id_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_admin_comment',
            field=models.BooleanField(default=False),
        ),
    ]
