# Generated by Django 5.0.2 on 2024-03-28 04:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comps', '0005_comment_is_admin_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_admin_comment',
            field=models.BooleanField(default=True),
        ),
    ]
