# Generated by Django 5.0.2 on 2024-03-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comps', '0006_complaint_closed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.IntegerField(choices=[(2, 'InProgress'), (3, 'Solved'), (1, 'Pending')], default=3),
        ),
    ]
