# Generated by Django 5.0.2 on 2024-03-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comps', '0007_alter_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'InProgress'), (3, 'Solved')], default=1),
        ),
    ]
