# Generated by Django 5.0.2 on 2024-03-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comps', '0008_alter_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.IntegerField(choices=[(3, 'Pending'), (2, 'InProgress'), (1, 'Solved')], default=3),
        ),
    ]
